:docinfo: shared

= Review

== Designing Software Architectures: A Practical Approach

Humberto Cervantes and Rick Kazman +
Addison Wesley, 2016

++++
<div style="padding-right:12px;float:left;">
<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=architectsmis-20&language=en_US&marketplace=amazon&region=US&placement=0134390784&asins=0134390784&linkId=5f5faa47e8e54870e3e1d339d68d0f62&show_border=true&link_opens_in_new_window=true"></iframe>
<div style="font-style:italic;text-align:center;font-size:65%;padding-top:4px">(paid link)</div>
</div>
++++

At the core of this book is Attribute-Driven Design (ADD), a software design method promoted by the Software Engineering Institute (SEI) and Carnegie Mellon University (CMU).
In other words, the book is not about software design in general but, as the subtitle suggests, a specific approach.
Approximately half the book is devoted to the method.
The bulk of that half is spent on case studies that describe its application in different domains.
The case studies do well at illustrating the use of the method.

The book opens with an explanation of software architecture and the need for more-formalized, more-repeatable design methods.
After the case studies, it briefly compares and contrasts ADD with other architectural methods.
Its penultimate discussion addresses how the design process might fit into software organizations.
The book concludes with two extensive appendices containing a catalog of design patterns, reference architectures, and the questionnaires that form an essential part of ADD.

Unless you have a specific interest in ADD, you'll probably find the introduction in link:Bass22.html[_Software Architecture in Practice_] sufficient.
(Indeed, Humberto Cervantes joins his co-author, Rick Kazman, as a contributor on the relevant chapter.)
The books have many similarities, but where _Software Architecture_ spends far more time on quality attributes, this volume invests its time on ADD.
If you only read one, go with _Software Architecture_.

'''

[.text-center]
link:books[Back to _Book Reviews_]

'''

++++
<div id="amzn-assoc-ad-c2f92062-7a05-41bc-be70-048948f34e84"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=c2f92062-7a05-41bc-be70-048948f34e84"></script>
++++
